#!/usr/bin/env python3

import io
import json

# aarch64.json from https://raw.githubusercontent.com/NeatMonster/AMIE/master/aarch64.json

with open('aarch64.json', 'rb') as h:
    amie = json.load(h)


msrx = amie['registers']['encodings']['MSR|MRS']

msrs = {}

for regname, bits in msrx.items():
    msrs[regname] = ''.join(bits)

regs = {}

for regname, bits in filter(lambda x: 'x' in x[1], msrs.items()):
    low = int(bits.replace('x', '0'), 2)
    high = int(bits.replace('x', '1'), 2)

    for ii in range(low, high + 1):
        regs[ii] = regname

for regname, bits in filter(lambda x: 'x' not in x[1], msrs.items()):
    key = int(bits, 2)
    regs[key] = regname

with io.open('src/msr.h', 'w', newline='\n') as h:
    h.write('// this file is autogenerated by msr.py\n')
    h.write('// do not edit\n')
    h.write('\n')
    h.write('#include <map>\n')
    h.write('using namespace std;\n')
    h.write('\n')
    h.write('map<uint32_t, const char *> msr = {\n');

    for key, val in regs.items():
        h.write('    {0x%06x, "%s"},\n' % (key, val))

    h.write('};\n')
